name: Deploy Laravel Application via SSH

on:
  push:
    branches:
      - gh-actions

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true ## Para no primeiro erro?!

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.gh-actions', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Execute tests (Unit and Feature tests) via Laravel tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test

    - name: Execute tests with pint
      run: composer pint:test

  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-interaction
      - name: Deploy application via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIV_KEY }}
          # port: ${{ secrets.PORT }}
          script: | #mudar depois para o caminho vir via ENV: https://github.com/appleboy/ssh-action/tree/master/#pass-environment-variable-to-shell-script
            whoami
            cd /var/www/projects/dev/tiagofranca/laravel-ci-cd
            ls -al
            git pull origin gh-actions
            bash ./ci-cd/scripts/sail-run.sh php -v
